### ISSUE TITLE
Check validation results

### ISSUE THREAD

**Issue by msimonson-psrc** [psrc/urbansim#64]
Everyone involved: @hanase , @jensenmj , @pcaballero 

Part of #61 
Follows task #62 and #63 

- [ ] mechanical validation:  did we build what we were supposed to?
- [ ] operational validation:  how does actor output compare to actual estimates?

**Comment by hanase** [comment]
Regarding operational validation:
The largest discrepancies to 2010 observed number of jobs are in fazes:
1. Boeing (faz 8000) - under-predicting 11,000 jobs
2. SeatTac (faz 3705) -   under-predicting about 9000 jobs
3. Microsoft (faz 5415) - under-predicting about 7000 jobs
