### ISSUE TITLE
Prepare LUTAC Review Package

### ISSUE THREAD

**Issue by msimonson-psrc** [psrc/urbansim#68]
LUMP meeting discussion - parameters:

* Years 2010, 2030 and 2040
* City, Tract and regional growth centers 
* Total HHs, Total Emp, and HH Pop
* Tables and Maps

**Comment by rlmaskin** [comment]
Stuff from SubRegional Controls Validation  (w TULU)

**Comment by rlmaskin** [comment]
Created a folder: J:\Projects\LandUseVision\iLUVUSim\Draft_Release_Materials
Has a map template, you just need to join in a tract level table (join on geoid- text field)

the table "AU_by_tract" is where the data needs to go
